### ISSUE TITLE
 is it a bug？

### ISSUE THREAD

**Issue by Dawei-Xia** [byemaxx/callCodeml#1]
hi
The script you developed is very convenient for butch-paml analysis. My question is that I have run but no progress,
Looking forward to your help! 
![图片](https://user-images.githubusercontent.com/64960057/128448956-c19d24f6-252b-4cde-bfe4-b35e9ec47d63.png)

**Comment by byemaxx** [comment]
Hi xzq,

Thank you for your interest in this script, I developed callCodeml to automatically calculate thousands of candidate genes and look for PSGs among them. Can you clearly describe the problem you encounter at runtime? Does your running directory generate a configuration file?

In addition, 1. Make sure you have added codeml to your environment variables. 2. The first parameter is the directory containing the multiple sequence alignment results in PAML format rather than a single file 3. Whether the result of multiple sequence alignment and the tree file are in the correct format. You can start by running a single gene using codeml to run the test.

Best,

Qing

**Comment by xzq-script** [comment]
Hi professor Wu,

Firstly, thank you for your prompt reply. For the PMAL software, I have successfully installed and tested a single ortholog-gene with paml align format. Then, I moved all the paml format sequence files to a directory named  “paml_txt”， and modified the sequence id to be consistent with the tree id. Finally, using callCodeml.py script to execute batch calculation with the command “python  callCodeml.py  paml_txt  Species.tree”.

Now, the program has one process directory  "WorkingDirctory_20210805-170031" , as well as WorkingDirctory_20210805-170031 sub-directories "*" that includes some other files,  the program seems to run but the process is always 0% without any dn/ds results.  No error, no progress (0%) and no dn/ds results, I don’t know how to solve this problem
 
![图片](https://user-images.githubusercontent.com/64960057/128466929-ab2f39ca-80b4-4ab4-bf7a-15c18956d2d6.png)

![图片](https://user-images.githubusercontent.com/64960057/128466902-5928028e-244d-4111-b789-6209a91cb69b.png)

Best
Qiang

**Comment by byemaxx** [comment]
Hi&nbsp;Qiang,
Are there any files in the working folder? If the program works, each gene will generate a folder containing the alte and null folders. Can you provide me with the files in the folder so that I can sort out the problems?


Best,


Qing




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月6日(星期五) 下午2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [byemaxx/callCodeml]  is it a bug？ (#1)





 
Hi professor Wu,
 
Firstly, thank you for your prompt reply. For the PMAL software, I have successfully installed and tested a single ortholog-gene with paml align format. Then, I moved all the paml format sequence files to a directory named  “paml_txt”， and modified the sequence id to be consistent with the tree id. Finally, using callCodeml.py script to execute batch calculation with the command “python  callCodeml.py  paml_txt  Species.tree”.
 
Now, the program has one process directory  "WorkingDirctory_20210805-170031" , as well as WorkingDirctory_20210805-170031 sub-directories "*" that includes some other files,  the program seems to run but the process is always 0% without any dn/ds results.  No error, no progress (0%) and no dn/ds results, I don’t know how to solve this problem
 

 

 
Best
 Qiang

**Comment by Dawei-Xia** [comment]
Hi professor Wu
 
Thank you for your prompt reply and constructive suggestion. The detailed error is TypeError: 'NoneType' object is not subscriptable.

![图片](https://user-images.githubusercontent.com/64960057/128468830-fb6ee666-51b5-4c0e-aab9-99931673a6d0.png)
best
Qing

**Comment by byemaxx** [comment]
Thank you for your information, I will give you response after fixing this.


Best,


Qing




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月6日(星期五) 下午2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [byemaxx/callCodeml]  is it a bug？ (#1)





 
Hi professor Wu
 
Thank you for your prompt reply and constructive suggestion. The detailed error is TypeError: 'NoneType' object is not subscriptable.
 

 best
 Qing

**Comment by byemaxx** [comment]
> Hi professor Wu
> 
> Thank you for your prompt reply and constructive suggestion. The detailed error is TypeError: 'NoneType' object is not subscriptable.
> 
> ![图片](https://user-images.githubusercontent.com/64960057/128468830-fb6ee666-51b5-4c0e-aab9-99931673a6d0.png)
> best
> Qing

I ran the test again on my computer (Linux version 5.10.16.3, Python 3.9.5) and everything worked fine. I noticed that your sequence name contains * . This may be the cause of the program error. I recommend that you rename the sequence name before running this.

Best,
Qing

**Comment by Dawei-Xia** [comment]
> 
> 
> > Hi professor Wu
> > Thank you for your prompt reply and constructive suggestion. The detailed error is TypeError: 'NoneType' object is not subscriptable.
> > ![图片](https://user-images.githubusercontent.com/64960057/128468830-fb6ee666-51b5-4c0e-aab9-99931673a6d0.png)
> > best
> > Qing
> 
> I ran the test again on my computer (Linux version 5.10.16.3, Python 3.9.5) and everything worked fine. I noticed that your sequence name contains * . This may be the cause of the program error. I recommend that you rename the sequence name before running this.
> 
> Best,
> Qing

Hi professor Wu

I checked the consistency of all sequence ids to ensure that there are no special characters, and determined the appropriate environmental conditions (python 3.9.5 ), there are still the following errors ：
![图片](https://user-images.githubusercontent.com/64960057/128512719-b6e1b544-dc50-435f-8c35-a06fa3248a34.png)
looking forward your help and reply
best
qiang

**Comment by byemaxx** [comment]
hi,

Can you provide 2 or 3 sample files?

**Comment by Dawei-Xia** [comment]
> 
> 
> hi,
> 
> Can you provide 2 or 3 sample files?

Hi
Thank you four your prompt reply. I have provided a batch of test files. 
Thanks again to professor Wu for this help.
[test.zip](https://github.com/byemaxx/callCodeml/files/6948866/test.zip)

**Comment by byemaxx** [comment]
> > hi,
> > Can you provide 2 or 3 sample files?
> 
> Hi
> Thank you four your prompt reply. I have provided a batch of test files.
> Thanks again to professor Wu for this help.
> [test.zip](https://github.com/byemaxx/callCodeml/files/6948866/test.zip)

Hi,

I use your files to test on my laptop, everything works. So please check your environment again. Check if there is a corresponding Python library installed, such as scipy, and add CodeML in your environment variable. ( I installed the PAML package in the Anaconda environment, and the CodeML program is included there.）

Best，

Qing

![image](https://user-images.githubusercontent.com/44231502/128597389-959b5a48-3160-47cb-9762-6636b1ea0136.png)

**Comment by Dawei-Xia** [comment]
> 
> 
> > > hi,
> > > Can you provide 2 or 3 sample files?
> > 
> > 
> > Hi
> > Thank you four your prompt reply. I have provided a batch of test files.
> > Thanks again to professor Wu for this help.
> > [test.zip](https://github.com/byemaxx/callCodeml/files/6948866/test.zip)
> 
> Hi,
> 
> I use your files to test on my laptop, everything works. So please check your environment again. Check if there is a corresponding Python library installed, such as scipy, and add CodeML in your environment variable. ( I installed the PAML package in the Anaconda environment, and the CodeML program is included there.）
> 
> Best，
> 
> Qing
> 
> ![image](https://user-images.githubusercontent.com/44231502/128597389-959b5a48-3160-47cb-9762-6636b1ea0136.png)

dear professor Wu
I am sure that there is no problem with the logical structure of callCODEML.py, because I have run batches and got some reliable results. However, there will still be "TypeError: 'NoneType' object is not subscriptable" errors in some gene sets. 
![图片](https://user-images.githubusercontent.com/64960057/128598356-4dc0fe1b-00e2-4c67-bfab-d0cc236670aa.png)

**Comment by byemaxx** [comment]
can you send the OG0007933 to me?

**Comment by Dawei-Xia** [comment]
[123.zip](https://github.com/byemaxx/callCodeml/files/6949003/123.zip)

**Comment by Dawei-Xia** [comment]
> 
> 
> can you send the OG0007933 to me?

Of course, I guess there may be special cases in some gene sets

**Comment by byemaxx** [comment]
It turns out that the sequence has problems.

![image](https://user-images.githubusercontent.com/44231502/128600006-46bc02f1-a4c5-494f-b1ab-4392a04419d5.png)

**Comment by Dawei-Xia** [comment]
> 
> 
> It turns out that the sequence has problems.
> 
> ![image](https://user-images.githubusercontent.com/44231502/128600006-46bc02f1-a4c5-494f-b1ab-4392a04419d5.png)

the sequence has problems？ Is it because there are too many gaps or other reasons？ I got orthology gene sets from Orthofinder，I don't know why some gene sets can and some can't.

**Comment by byemaxx** [comment]
Perhaps you can get the format requirements from the PAML handbook, which you can easily find online. In addition, I may update this script in the future to add detection and skip functionality for error sequences.

Best,

Qing
